using ArcadeLibraryManager.Core;
using Microsoft.Data.Sqlite;
using System.Text;
using System.Xml.Linq;

public static class LaunchBoxChecks {
 private static void Check(bool value,string reason){if(!value)throw new Exception("LaunchBox check failed: "+reason);}
 private static async Task Reject(Func<Task> operation,string reason){try{await operation();}catch(InvalidOperationException){return;}throw new Exception("Expected rejection: "+reason);}
 public static async Task RunAsync(string root) {
  var work=Path.Combine(root,"launchbox-"+Guid.NewGuid().ToString("N"));var lb=Path.Combine(work,"LaunchBox");var tp=Path.Combine(work,"TeknoParrot");var profiles=Path.Combine(tp,"UserProfiles");Directory.CreateDirectory(profiles);Directory.CreateDirectory(Path.Combine(lb,"Data","Platforms"));Directory.CreateDirectory(Path.Combine(lb,"Metadata"));
  var settings=new AppSettings{LaunchBoxPath=lb,TeknoParrotPath=tp,PlatformName="TeknoParrot",CachePath=Path.Combine(work,"cache")};
  File.WriteAllText(Path.Combine(lb,"Data","Platforms.xml"),"<LaunchBox><Platform><Name>TeknoParrot</Name><ScrapeAs>Arcade</ScrapeAs></Platform><PlatformFolder><Platform>TeknoParrot</Platform><MediaType>Theme Video</MediaType><FolderPath>CustomThemes</FolderPath></PlatformFolder></LaunchBox>");
  File.WriteAllText(Path.Combine(lb,"Data","Emulators.xml"),new XElement("LaunchBox",new XElement("Emulator",new XElement("ID","emu"),new XElement("Title","My custom emulator"),new XElement("ApplicationPath",Path.Combine(tp,"TeknoParrotUi.exe")),new XElement("CommandLine","--profile=%romfile%.xml"),new XElement("FileNameWithoutExtensionAndPath","true"),new XElement("AutoHotkeyScript","existing script"))).ToString());
  Directory.CreateDirectory(tp); File.WriteAllText(Path.Combine(tp, "TeknoParrotUi.exe"), "inert executable fixture");
  XElement G(string id,string profile)=>new("Game",new XElement("ID",id),new XElement("Title",profile+" curated title"),new XElement("ApplicationPath",Path.Combine("..","OldLocation","UserProfiles",profile+".xml")),new XElement("Emulator","emu"),new XElement("DatabaseID",22),new XElement("Favorite","true"),new XElement("PlayCount",17),new XElement("Notes","My manual notes"),new XElement("Genre","Hand curated genre"),new XElement("UnknownFutureField",new XElement("Child","keep me")));
  XElement A(string id,string profile)=>new("AdditionalApplication",new XElement("Id",id),new XElement("GameID","alpha-guid"),new XElement("ApplicationPath",Path.Combine("..","OldLocation","UserProfiles",profile+".xml")),new XElement("EmulatorId","emu"),new XElement("Priority",3),new XElement("UseEmulator","true"));
  var hook=new XElement("AdditionalApplication",new XElement("Id","hook"),new XElement("GameID","alpha-guid"),new XElement("ApplicationPath","DemulShooter/start.bat"),new XElement("AutoRunBefore","true"),new XElement("WaitForExit","true"),new XElement("Priority",1));
  var document=new XDocument(new XElement("LaunchBox",G("alpha-guid","alpha"),A("beta-guid","beta"),G("duplicate-main","collision"),A("duplicate-extra","collision"),hook,new XElement("AlternateName",new XElement("GameID","alpha-guid"),new XElement("Name","My other title"))));var platform=Path.Combine(lb,"Data","Platforms","TeknoParrot.xml");document.Save(platform);var original=File.ReadAllBytes(platform);
  const string meaningfulNotes="  Curated first line\nSecond line with trailing spaces  ";
  document.Root!.Element("Game")!.SetElementValue("Notes",meaningfulNotes);
  document.Root.Add(new XComment("Preserve this user's comment"),new XProcessingInstruction("custom","preserve-me"),
   new XElement("UnknownMixed",new XText("before "),new XElement("Inner","middle"),new XText(" after")),
   new XElement("UnknownPreservedSpace",new XAttribute(XNamespace.Xml+"space","preserve"),new XText("  "),new XElement("Inner","keep"),new XText("\n  ")),
   new XElement("UnknownWhitespaceLeaf","   "),new XElement("UnknownCData",new XCData("  literal <text>\n ")));
  document.Save(platform);original=File.ReadAllBytes(platform);
  var games=new List<GameRecord>();foreach(var id in new[]{"alpha","beta","collision","delta","broken","twopath"}){var payload=Path.Combine(work,id+".bin");if(id!="broken")File.WriteAllBytes(payload,new byte[]{1,2,3});var path=Path.Combine(profiles,id+".xml");new XDocument(new XElement("GameProfile",new XElement("GamePath",payload),new XElement("HasTwoExecutables",id=="twopath"?"true":"false"),new XElement("GamePath2",""),new XElement("Controls","untouched"))).Save(path);games.Add(new(){Id=id,Name=id,UserProfilePath=path,Genre="Arcade",Year="2000"});}
  var metadataPath=Path.Combine(lb,"Metadata","LaunchBox.Metadata.db");
  using(var con=new SqliteConnection(new SqliteConnectionStringBuilder{DataSource=metadataPath,Pooling=false}.ToString())){con.Open();using var command=con.CreateCommand();command.CommandText="CREATE TABLE Games(DatabaseID INTEGER PRIMARY KEY,Name TEXT,Platform TEXT,Overview TEXT,Genres TEXT,Developer TEXT,Publisher TEXT);INSERT INTO Games VALUES(100,'delta','Arcade','Database description','Action','Studio','Publisher'),(22,'alpha database title','Arcade','Database notes must not replace curated notes','Action','Database Studio','Database Publisher');";command.ExecuteNonQuery();}
  var metadataOriginal=File.ReadAllBytes(metadataPath);
  var running=false;var service=new LaunchBoxService(()=>running,VolumeHealthChecks.CleanProvider());var plan=await service.PreviewAsync(settings,games);
  Check(plan.Items.Single(i=>i.ProfileId=="delta").Action=="Add","new exact profile planned");Check(plan.Items.Single(i=>i.ProfileId=="beta").Action=="Update","alternate entry matched, not duplicated");Check(plan.Items.Single(i=>i.ProfileId=="collision").Action=="NeedsReview","collision flagged");Check(plan.Items.Count(i=>i.Action=="NotReady")==2,"missing primary and secondary excluded");Check(plan.MediaFolders["Theme Video"]==Path.Combine(lb,"CustomThemes"),"media override honored");
  var blockedService=new LaunchBoxService(()=>false,new VolumeHealthService((path,ct)=>Task.FromResult(new VolumeHealthResult(path,"fixture","NTFS",VolumeHealthState.Dirty,"Test"))));try{await blockedService.ApplyAsync(plan);throw new Exception("Dirty LaunchBox commit accepted");}catch(VolumeHealthException){}Check(File.ReadAllBytes(platform).SequenceEqual(original),"dirty guard precedes XML writes");
  running=true;await Reject(()=>service.ApplyAsync(plan),"open LaunchBox");running=false;Check(File.ReadAllBytes(platform).SequenceEqual(original),"open-app refusal made no changes");File.AppendAllText(platform,"\n");await Reject(()=>service.ApplyAsync(plan),"concurrent data edit");File.WriteAllBytes(platform,original);
  plan=await service.PreviewAsync(settings,games);var result=await service.ApplyAsync(plan);Check(result.Succeeded==3,"one add and two path updates committed");var changed=XDocument.Load(platform);var alpha=changed.Root!.Elements("Game").Single(e=>(string?)e.Element("ID")=="alpha-guid");Check((string?)alpha.Element("Favorite")=="true"&&(string?)alpha.Element("PlayCount")=="17","history/favorite preserved");Check((string?)alpha.Element("Notes")==meaningfulNotes&&(string?)alpha.Element("DatabaseID")=="22","curated multiline whitespace and DB ID preserved");Check(alpha.Element("UnknownFutureField")!.Element("Child")!.Value=="keep me","unknown nodes preserved");Check(XNode.DeepEquals(hook,changed.Root.Elements("AdditionalApplication").Single(e=>(string?)e.Element("Id")=="hook")),"hook fields/order preserved");Check(changed.Root.Elements("Game").Count()==3,"only missing main entry added");Check((string?)changed.Root.Elements("Game").Single(e=>(string?)e.Element("Title")=="delta").Element("DatabaseID")=="100","exact metadata filled");
  Check((string?)alpha.Element("Publisher")=="Database Publisher"&&(string?)alpha.Element("Developer")=="Database Studio"&&(string?)alpha.Element("Genre")=="Hand curated genre","local metadata fills only missing existing game fields and preserves curated genre");
  var delta=changed.Root.Elements("Game").Single(e=>(string?)e.Element("Title")=="delta");Check((string?)delta.Element("Notes")=="Database description"&&(string?)delta.Element("Genre")=="Action","local metadata fills blank fields on a newly added game");
  var serialized=File.ReadAllText(platform);Check(!serialized.Contains("</Game><Game>")&&!serialized.Contains("<Game><ID>"),"new records and fields are indented instead of concatenated");
  Check(serialized.Contains("<CommandLine />")&&!serialized.Contains("<CommandLine></CommandLine>"),"new empty scalar fields use LaunchBox self-closing form");
  var preserved=XDocument.Load(platform,LoadOptions.PreserveWhitespace);
  Check(preserved.Root!.Nodes().OfType<XComment>().Any(c=>c.Value=="Preserve this user's comment")&&preserved.Root.Nodes().OfType<XProcessingInstruction>().Any(p=>p.Target=="custom"&&p.Data=="preserve-me"),"comments and processing instructions survive formatting");
  foreach(var name in new[]{"UnknownMixed","UnknownPreservedSpace","UnknownWhitespaceLeaf","UnknownCData"})Check(XNode.DeepEquals(document.Root.Element(name),preserved.Root.Element(name)),"meaningful mixed/whitespace/CDATA content preserved: "+name);
  var repeat=await service.PreviewAsync(settings,games);Check(!repeat.CanApply,"rerun idempotent");var betaIdentity=LaunchBoxService.FindGameIdentity(settings,games.Single(g=>g.Id=="beta"));Check(betaIdentity?.IsAdditionalApplication==true&&betaIdentity.GameGuid=="alpha-guid","additional-app identity parent preserved");
  await service.RollbackAsync(Path.Combine(Path.GetDirectoryName(plan.BackupPath)!,"rollback.json"));Check(File.ReadAllBytes(platform).SequenceEqual(original),"atomic backup rollback restores exact bytes");
  var stale=await service.PreviewAsync(settings,games);File.AppendAllText(games.Single(g=>g.Id=="delta").UserProfilePath,"\n");await Reject(()=>service.ApplyAsync(stale),"changed user profile");
  var localSettings=new AppSettings{LaunchBoxPath=Path.Combine(work,"Local metadata fixture"),CachePath=Path.Combine(work,"unused cache")};
  var localDatabase=Path.Combine(localSettings.LaunchBoxPath,"Metadata","LaunchBox.Metadata.db");Directory.CreateDirectory(Path.GetDirectoryName(localDatabase)!);
  using(var connection=new SqliteConnection(new SqliteConnectionStringBuilder{DataSource=localDatabase,Pooling=false}.ToString())){connection.Open();using var command=connection.CreateCommand();command.CommandText="CREATE TABLE Games(DatabaseID INTEGER PRIMARY KEY,Name TEXT,Platform TEXT,Overview TEXT,ReleaseYear INTEGER);INSERT INTO Games VALUES(5,'Exact','Arcade','Exact notes',1997),(6,'Other','Arcade',NULL,NULL),(7,'Ambiguous','Arcade',NULL,NULL),(8,'Ambiguous','Arcade',NULL,NULL),(9,'Console Only','Console',NULL,NULL);CREATE TABLE GameAlternateTitles(DatabaseID INTEGER,AlternateName TEXT);INSERT INTO GameAlternateTitles VALUES(5,'Alias'),(5,'Alias'),(6,'Shared Alias'),(5,'Shared Alias');";command.ExecuteNonQuery();}
  var databaseBefore=File.ReadAllBytes(localDatabase);
  using(var catalog=LaunchBoxMetadataService.TryOpen(localSettings)){Check(catalog?.FindExact("Exact")?.DatabaseId==5,"local SQLite metadata read");Check(catalog?.FindExact("Other")?.DatabaseId==6,"adjacent database records read");Check(catalog?.FindExact(" Alias ")?.DatabaseId==5,"exact alias matches once despite repeated same-game aliases");Check(catalog?.FindExact("exact")?.DatabaseId==5,"exact title matching ignores case");Check(catalog?.FindExact("Exact Rev 2")==null,"edition suffix not stripped");Check(catalog?.FindExact("Ambiguous")==null&&catalog?.FindExact("Shared Alias")==null,"ambiguous titles and aliases are rejected");Check(catalog?.FindExact("Console Only")==null,"title matching stays on the Arcade platform");Check(catalog?.FindExact("Unrelated custom title",5)?.DatabaseId==5,"existing database identity remains authoritative");Check(catalog?.FindExact("Exact")?.Fields["ReleaseDate"]=="1997-01-01","release year supplies missing date");}
  Check(File.ReadAllBytes(localDatabase).SequenceEqual(databaseBefore)&&!Directory.Exists(localSettings.CachePath),"catalog reads preserve local database and do not create a cache");
  using(var absent=LaunchBoxMetadataService.TryOpen(new AppSettings{LaunchBoxPath=Path.Combine(work,"missing LaunchBox"),CachePath=Path.Combine(work,"missing cache")})){Check(absent==null,"absent local metadata returns no catalog without a download");}
  Check(File.ReadAllBytes(metadataPath).SequenceEqual(metadataOriginal),"sync left its local metadata database unchanged");
  await CheckRegionSelectionAsync(Path.Combine(work,"regions"));
  await CheckLoaderCombinationsAsync(Path.Combine(work,"loaders"));
  Console.WriteLine("LaunchBox checks passed: identity/variants, duplicate conflicts, primary+secondary readiness, media override, open process, concurrent changes, preservation, idempotency, rollback, local read-only metadata.");
 }
 private static async Task CheckRegionSelectionAsync(string work) {
  var lb=Path.Combine(work,"LaunchBox");var tp=Path.Combine(work,"TeknoParrot");var profiles=Path.Combine(tp,"UserProfiles");var templates=Path.Combine(tp,"GameProfiles");var metadata=Path.Combine(tp,"Metadata");
  foreach(var dir in new[]{profiles,templates,metadata,Path.Combine(lb,"Data","Platforms")})Directory.CreateDirectory(dir);
  var settings=new AppSettings{LaunchBoxPath=lb,TeknoParrotPath=tp,PlatformName="TeknoParrot",FillMissingMetadata=false};
  var platform=Path.Combine(lb,"Data","Platforms","TeknoParrot.xml");
  new XElement("LaunchBox",new XElement("Emulator",new XElement("ID","emu"),new XElement("ApplicationPath",Path.Combine(tp,"TeknoParrotUi.exe")),new XElement("CommandLine","--profile=%romfile%"))).Save(Path.Combine(lb,"Data","Emulators.xml"));
  Directory.CreateDirectory(tp); File.WriteAllText(Path.Combine(tp, "TeknoParrotUi.exe"), "inert executable fixture");
  void Reset(params XElement[] nodes)=>new XDocument(new XElement("LaunchBox",nodes)).Save(platform);
  GameRecord Profile(string id,string title) {
   var payload=Path.Combine(work,id+".bin");File.WriteAllBytes(payload,new byte[]{1});
   var profile=Path.Combine(profiles,id+".xml");new XElement("GameProfile",new XElement("GamePath",payload)).Save(profile);new XElement("GameProfile",new XElement("DevOnly",false)).Save(Path.Combine(templates,id+".xml"));
   File.WriteAllText(Path.Combine(metadata,id+".json"),System.Text.Json.JsonSerializer.Serialize(new{game_name=title}));
   return new(){Id=id,Name=title,UserProfilePath=profile,GamePath=payload,Installed=true,PathsValid=true};
  }
  XElement Existing(string id,GameRecord game,string? title=null)=>new("Game",new XElement("ID",id),new XElement("Title",title??game.Name),new XElement("ApplicationPath",game.UserProfilePath),new XElement("Emulator","emu"),new XElement("Favorite",true),new XElement("PlayCount",42),new XElement("PlayTime",700),new XElement("Notes","Curated notes"));
  var usa=Profile("totlviceu","Total Vice (USA)");var world=Profile("totlvicew","Total Vice (World)");var japan=Profile("totlvicej","Total Vice (Japan)");var europe=Profile("totlvicee","Total Vice (Europe)");var sequel=Profile("totlvice2","Total Vice 2 (Japan)");
  var all=new[]{japan,europe,world,usa,sequel};var service=new LaunchBoxService(()=>false,VolumeHealthChecks.CleanProvider());Reset();var before=File.ReadAllBytes(platform);
  var plan=await service.PreviewAsync(settings,all);
  Check(plan.Items.Count(i=>i.Action=="Add")==2&&plan.Items.Single(i=>i.ProfileId==usa.Id).Action=="Add"&&plan.Items.Single(i=>i.ProfileId==sequel.Id).Action=="Add","USA wins locale group while sequel remains separate");
  Check(plan.Items.Count(i=>i.Action=="SkippedVariant")==3&&plan.Items.Where(i=>i.Action=="SkippedVariant").All(i=>!i.Selected),"other locales unselected with an explicit reason");Check(File.ReadAllBytes(platform).SequenceEqual(before),"region preview is read-only");
  var subset=await service.PreviewAsync(settings,new[]{japan});Check(!subset.CanApply&&subset.Items.Single().Action=="SkippedVariant"&&subset.Items.Single().Detail.Contains(usa.Name),"subset cannot bypass a ready preferred catalog profile");
  File.Delete(usa.GamePath);var fallback=await service.PreviewAsync(settings,all);Check(fallback.Items.Single(i=>i.ProfileId==world.Id).Action=="Add"&&fallback.Items.Single(i=>i.ProfileId==usa.Id).Action=="NotReady","actual missing USA launch file makes World the preferred ready version");
  File.Delete(world.GamePath);fallback=await service.PreviewAsync(settings,all);Check(fallback.Items.Count(i=>i.Action=="Add")==2&&fallback.Items.Count(i=>i.Action=="SkippedVariant")==1,"one other region is selected when USA and World are unavailable");File.WriteAllBytes(usa.GamePath,new byte[]{1});File.WriteAllBytes(world.GamePath,new byte[]{1});
  var original=Existing("persistent-id",japan);var hook=new XElement("AdditionalApplication",new XElement("Id","keep-hook"),new XElement("GameID","persistent-id"),new XElement("ApplicationPath","before.bat"),new XElement("AutoRunBefore",true));
  Reset(original,hook);var upgrade=await service.PreviewAsync(settings,new[]{usa});Check(upgrade.Items.Single().Action=="Update"&&upgrade.Items.Single().GameGuid=="persistent-id","preferred USA repoints an existing regional entry rather than adding a game");await service.ApplyAsync(upgrade);
  var updated=XDocument.Load(platform);var game=updated.Root!.Element("Game")!;Check(updated.Root.Elements("Game").Count()==1&&(string?)game.Element("ID")=="persistent-id"&&(string?)game.Element("Title")==usa.Name,"preferred update retains game identity and updates the canonical regional title");
  Check((string?)game.Element("PlayCount")=="42"&&(string?)game.Element("PlayTime")=="700"&&(string?)game.Element("Favorite")=="true"&&(string?)game.Element("Notes")=="Curated notes"&&XNode.DeepEquals(hook,updated.Root.Element("AdditionalApplication")),"regional upgrade preserves favorites, play history, notes and launch hooks");
  Check(LaunchBoxService.FindGameIdentity(settings,usa)?.GameGuid=="persistent-id","preferred profile resolves to retained LaunchBox ID");Check(!(await service.PreviewAsync(settings,all.Where(g=>g.Id!=sequel.Id))).CanApply,"regional sync remains idempotent after preferred update");
  Reset(Existing("curated",japan,"My favorite shooter"));var curated=await service.PreviewAsync(settings,new[]{usa});await service.ApplyAsync(curated);Check((string?)XDocument.Load(platform).Root!.Element("Game")!.Element("Title")=="My favorite shooter","custom game title survives the profile change");
  XElement Support(string gameId,string controller="controller-one",string level="3")=>new("GameControllerSupport",new XElement("ControllerId",controller),new XElement("GameId",gameId),new XElement("SupportLevel",level),new XElement("CustomControllerNote","Preserve this controller setting"));
  Reset(Existing("japan-id",japan),Existing("world-id",world),Support("japan-id"),Support("world-id"),Support("japan-id","controller-two","1"));before=File.ReadAllBytes(platform);var duplicates=await service.PreviewAsync(settings,all.Where(g=>g.Id!=sequel.Id));Check(duplicates.Items.Single(i=>i.ProfileId==usa.Id).Action=="Consolidate"&&duplicates.Items.Where(i=>i.ProfileId!=usa.Id).All(i=>i.Action=="SkippedVariant"&&!i.Selected),"regional duplicates plan one preferred consolidation");Check(File.ReadAllBytes(platform).SequenceEqual(before),"consolidation preview preserves XML bytes");await service.ApplyAsync(duplicates);var consolidated=XDocument.Load(platform).Root!.Elements("Game").Single();Check((string?)consolidated.Element("ID")=="world-id"&&(string?)consolidated.Element("Title")==usa.Name&&(string?)consolidated.Element("PlayCount")=="84","preferred absent USA promotes best existing regional game and merges history");Check(File.ReadAllBytes(duplicates.BackupPath).SequenceEqual(before),"removed regional entries are preserved in the exact backup");
  var supportRows=XDocument.Load(platform).Root!.Elements("GameControllerSupport").ToList();Check(supportRows.Count==2&&supportRows.All(e=>(string?)e.Element("GameId")=="world-id")&&supportRows.All(e=>(string?)e.Element("CustomControllerNote")=="Preserve this controller setting"),"regional controller links reparent, equivalent controller rows deduplicate, and custom settings survive");Check(!(await service.PreviewAsync(settings,new[]{usa,japan,world})).CanApply,"controller support consolidation stays idempotent");
  Reset(Existing("japan-id",japan),Existing("world-id",world),Support("japan-id"),Support("world-id",level:"2"));var supportConflict=await service.PreviewAsync(settings,new[]{usa});Check(supportConflict.Items.Single().Action=="NeedsReview"&&supportConflict.Items.Single().Detail.Contains("conflicting support levels"),"different regional controller support levels require review instead of guessing");
  var customSupport=Support("world-id");customSupport.SetElementValue("CustomControllerNote","different user setting");Reset(Existing("japan-id",japan),Existing("world-id",world),Support("japan-id"),customSupport);supportConflict=await service.PreviewAsync(settings,new[]{usa});Check(supportConflict.Items.Single().Action=="NeedsReview"&&supportConflict.Items.Single().Detail.Contains("custom support settings"),"conflicting custom controller settings are preserved for review");
  var malformedSupport=Support("unrelated-id");malformedSupport.Add(new XElement("GameId","japan-id"));Reset(Existing("japan-id",japan),Existing("world-id",world),malformedSupport);supportConflict=await service.PreviewAsync(settings,new[]{usa});Check(supportConflict.Items.Single().Action=="NeedsReview","multiple GameId fields cannot hide an orphaned controller reference");
  Reset(new XElement("Game",new XElement("ID","custom-launch"),new XElement("Title",japan.Name),new XElement("ApplicationPath","CustomLauncher.exe")));var ambiguous=await service.PreviewAsync(settings,new[]{usa});Check(ambiguous.Items.Single().Action=="NeedsReview"&&!ambiguous.CanApply,"title-only family match blocks a second game without rewriting a custom launcher");
 }
 private static async Task CheckLoaderCombinationsAsync(string work) {
  var lb=Path.Combine(work,"LaunchBox");var tp=Path.Combine(work,"TeknoParrot");var profiles=Path.Combine(tp,"UserProfiles");var metadata=Path.Combine(tp,"Metadata");var templates=Path.Combine(tp,"GameProfiles");
  foreach(var directory in new[]{profiles,metadata,templates,Path.Combine(lb,"Data","Platforms"),Path.Combine(lb,"Data","Playlists")})Directory.CreateDirectory(directory);
  var settings=new AppSettings{LaunchBoxPath=lb,TeknoParrotPath=tp,PlatformName="TeknoParrot",FillMissingMetadata=false};var platform=Path.Combine(lb,"Data","Platforms","TeknoParrot.xml");
  new XElement("LaunchBox",new XElement("Emulator",new XElement("ID","emu"),new XElement("ApplicationPath",Path.Combine(tp,"TeknoParrotUi.exe")),new XElement("CommandLine","--profile=%romfile%"))).Save(Path.Combine(lb,"Data","Emulators.xml"));
  Directory.CreateDirectory(tp); File.WriteAllText(Path.Combine(tp, "TeknoParrotUi.exe"), "inert executable fixture");
  GameRecord Profile(string id,string name,string emulator) {var payload=Path.Combine(work,id+".bin");File.WriteAllBytes(payload,new byte[]{1});var user=Path.Combine(profiles,id+".xml");new XElement("GameProfile",new XElement("GamePath",payload)).Save(user);new XElement("GameProfile",new XElement("EmulatorType",emulator)).Save(Path.Combine(templates,id+".xml"));File.WriteAllText(Path.Combine(metadata,id+".json"),System.Text.Json.JsonSerializer.Serialize(new{game_name=name}));return new(){Id=id,Name=name,UserProfilePath=user,Emulator=emulator,Installed=true,PathsValid=true};}
  var legacy=Profile("StarTrekVoyager","Star Trek Voyager","Lindbergh");var elf2=Profile("StarTrekVoyagerElf2","Star Trek Voyager (ElfLoader2)","ElfLdr2");
  XElement Game(string id,GameRecord profile,int count)=>new("Game",new XElement("ID",id),new XElement("Title",profile.Name),new XElement("ApplicationPath",profile.UserProfilePath),new XElement("Emulator","emu"),new XElement("CommandLine",""),new XElement("Favorite",id=="new-id"),new XElement("PlayCount",count),new XElement("PlayTime",count*10),new XElement("LastPlayedDate",id=="new-id"?"2026-09-20T12:00:00Z":"2026-09-10T12:00:00Z"),new XElement("Notes",id+" curated notes"),new XElement("UnknownFutureField",new XElement("Child",id+" data")));
  var oldGame=Game("old-id",legacy,7);var newGame=Game("new-id",elf2,3);
  var hook=new XElement("AdditionalApplication",new XElement("Id","parent-hook"),new XElement("GameID","old-id"),new XElement("ApplicationPath","before.bat"),new XElement("AutoRunBefore",true));
  var manual=new XElement("AdditionalApplication",new XElement("Id","manual-tool"),new XElement("GameID","new-id"),new XElement("ApplicationPath","optional.exe"),new XElement("AutoRunBefore",false),new XElement("AutoRunAfter",false));
  var alias=new XElement("AlternateName",new XElement("GameID","new-id"),new XElement("Name","Voyager alias"));
  void Reset(params XElement[] nodes)=>new XDocument(new XElement("LaunchBox",nodes)).Save(platform);
  XElement LoaderSupport(string gameId,string level="3")=>new("GameControllerSupport",new XElement("ControllerId","controller-fixture"),new XElement("GameId",gameId),new XElement("SupportLevel",level),new XElement("CustomSetting","controller user data"));
  Reset(oldGame,newGame,hook,manual,alias,LoaderSupport("old-id"),LoaderSupport("new-id"));var original=File.ReadAllBytes(platform);var service=new LaunchBoxService(()=>false,VolumeHealthChecks.CleanProvider());
  var plan=await service.PreviewAsync(settings,new[]{elf2});Check(plan.Items.Single().Action=="Combine"&&plan.CanApply&&plan.Items.Single().GameGuid=="old-id","verified loader pair combines into existing original ID");Check(File.ReadAllBytes(platform).SequenceEqual(original),"combination preview is read-only");
  await service.ApplyAsync(plan);var combined=XDocument.Load(platform);var game=combined.Root!.Elements("Game").Single();
  Check((string?)game.Element("ID")=="old-id"&&(string?)game.Element("Title")==legacy.Name&&Path.GetFullPath(Path.Combine(lb,game.Element("ApplicationPath")!.Value))==elf2.UserProfilePath,"one retained game defaults to ELF2 while preserving original title and ID");Check((string?)game.Element("Version")==elf2.Id,"default version identifies the ELF2 loader");
  Check((string?)game.Element("PlayCount")=="10"&&(string?)game.Element("PlayTime")=="100"&&(string?)game.Element("Favorite")=="true"&&(string?)game.Element("LastPlayedDate")=="2026-09-20T12:00:00Z"&&(string?)game.Element("Notes")=="old-id curated notes","play history merged and parent metadata retained");
  var apps=combined.Root.Elements("AdditionalApplication").ToList();Check(apps.Count==4&&apps.Count(e=>(string?)e.Element("UseEmulator")=="true")==2,"both loader launch options added without replacing existing applications");
  Check(XNode.DeepEquals(hook,apps.Single(e=>(string?)e.Element("Id")=="parent-hook")),"original automatic hook preserved exactly");Check((string?)apps.Single(e=>(string?)e.Element("Id")=="manual-tool").Element("GameID")=="old-id"&&(string?)combined.Root.Element("AlternateName")!.Element("GameID")=="old-id","removed game's manual applications and alternate names reparented");
  Check(File.ReadAllBytes(plan.BackupPath).SequenceEqual(original),"complete secondary metadata and unknown fields retained in byte-exact backup");
  var loaderSupport=combined.Root.Elements("GameControllerSupport").Single();Check((string?)loaderSupport.Element("GameId")=="old-id"&&(string?)loaderSupport.Element("CustomSetting")=="controller user data","ELF combination deduplicates controller links on retained ID without losing custom settings");
  var identity=LaunchBoxService.FindGameIdentity(settings,elf2);Check(identity is {Duplicate:false,IsAdditionalApplication:false,GameGuid:"old-id"},"intentional ELF2 main/default mirror resolves as one media identity");Check(LaunchBoxService.FindGameIdentity(settings,legacy) is {IsAdditionalApplication:true,GameGuid:"old-id"},"legacy loader resolves to retained game's alternate launch option");
  var repeat=await service.PreviewAsync(settings,new[]{legacy,elf2});Check(!repeat.CanApply&&repeat.Items.Single(i=>i.ProfileId==elf2.Id).Action=="Unchanged","already-combined Voyager is idempotent and default mirror is accepted");
  await service.RollbackAsync(Path.Combine(Path.GetDirectoryName(plan.BackupPath)!,"rollback.json"));Check(File.ReadAllBytes(platform).SequenceEqual(original),"combined library rollback restores both game IDs and all child references");
  Reset(oldGame,newGame,LoaderSupport("old-id"),LoaderSupport("new-id","1"));var controllerReview=await service.PreviewAsync(settings,new[]{elf2});Check(controllerReview.Items.Single().Action=="NeedsReview"&&controllerReview.Items.Single().Detail.Contains("conflicting support levels"),"ELF combination also reviews conflicting controller support");File.WriteAllBytes(platform,original);
  var external=Path.Combine(lb,"Data","Playlists","Favorites.xml");new XElement("LaunchBox",new XElement("PlaylistGame",new XElement("GameId","new-id"))).Save(external);
  var blocked=await service.PreviewAsync(settings,new[]{elf2});Check(blocked.Items.Single().Action=="Combine"&&blocked.CanApply,"supported playlist references are included in combination");var originalPlaylist=File.ReadAllBytes(external);await service.ApplyAsync(blocked);Check(XDocument.Load(external).Root!.Element("PlaylistGame")!.Element("GameId")!.Value=="old-id","external playlist follows the surviving game ID");await service.RollbackAsync(Path.Combine(Path.GetDirectoryName(blocked.BackupPath)!,"rollback.json"));Check(File.ReadAllBytes(platform).SequenceEqual(original)&&File.ReadAllBytes(external).SequenceEqual(originalPlaylist),"multi-file rollback restores platform and playlist bytes together");File.Delete(external);
  var stale=await service.PreviewAsync(settings,new[]{elf2});new XElement("LaunchBox",new XElement("PlaylistGame",new XElement("GameId","new-id"))).Save(external);await Reject(()=>service.ApplyAsync(stale),"new external reference after preview");Check(File.ReadAllBytes(platform).SequenceEqual(original),"newly referenced game ID remains untouched");File.Delete(external);
  var automatic=new XElement(manual);automatic.SetElementValue("AutoRunAfter",true);Reset(oldGame,newGame,automatic);blocked=await service.PreviewAsync(settings,new[]{elf2});Check(blocked.Items.Single().Action=="NeedsReview"&&blocked.Items.Single().Detail.Contains("automatic launch hooks"),"secondary automatic hooks block behavior-changing consolidation");
  var unsupported=new XElement(newGame);unsupported.SetElementValue("PlayTime","a long time");Reset(oldGame,unsupported);blocked=await service.PreviewAsync(settings,new[]{elf2});Check(blocked.Items.Single().Action=="NeedsReview"&&blocked.Items.Single().Detail.Contains("PlayTime"),"unparseable history blocks combination");
  var custom=new XElement(newGame);custom.SetElementValue("CommandLine","custom override");Reset(oldGame,custom);blocked=await service.PreviewAsync(settings,new[]{elf2});Check(blocked.Items.Single().Action=="NeedsReview","custom per-game command blocks combination");
  Reset(oldGame);var promote=await service.PreviewAsync(settings,new[]{elf2});Check(promote.Items.Single().Action=="Combine","single original game is promoted while preserving original loader choice");await service.ApplyAsync(promote);Check(XDocument.Load(platform).Root!.Elements("Game").Count()==1&&XDocument.Load(platform).Root!.Elements("AdditionalApplication").Count()==2,"single game promotion produces two loader choices and one game");
  var mirror=new XElement("AdditionalApplication",new XElement("Id","mirror-only"),new XElement("GameID","new-id"),new XElement("ApplicationPath",elf2.UserProfilePath),new XElement("AutoRunBefore",false),new XElement("AutoRunAfter",false));Reset(newGame,mirror);var mirrored=await service.PreviewAsync(settings,new[]{elf2});Check(mirrored.Items.Single().Action=="Unchanged"&&!mirrored.CanApply,"a sole default mirror is intentional even without a legacy launch option");
  var existingElf2Choice=new XElement(mirror);existingElf2Choice.SetElementValue("Id","existing-elf2-choice");existingElf2Choice.SetElementValue("GameID","old-id");Reset(oldGame,existingElf2Choice);var switchDefault=await service.PreviewAsync(settings,new[]{elf2});Check(switchDefault.Items.Single().Action=="Combine","original main plus ELF2 manual choice promotes ELF2 without treating a different profile as a mirror");await service.ApplyAsync(switchDefault);var switched=XDocument.Load(platform);Check(switched.Root!.Elements("AdditionalApplication").Count()==2&&switched.Root.Elements("AdditionalApplication").Count(e=>(string?)e.Element("Id")=="existing-elf2-choice")==1,"existing ELF2 launch choice is retained and only missing original launch choice is added");Check(!(await service.PreviewAsync(settings,new[]{legacy,elf2})).CanApply,"promoted pre-existing ELF2 choice remains idempotent");
  var loaderHook=new XElement(mirror);loaderHook.SetElementValue("GameID","old-id");loaderHook.SetElementValue("AutoRunBefore",true);Reset(oldGame,loaderHook);blocked=await service.PreviewAsync(settings,new[]{elf2});Check(blocked.Items.Single().Action=="NeedsReview","automatic loader options cannot become duplicate startup launches");
  foreach(var reference in new[]{new XElement("UnknownGameID","new-id"),new XElement("UnknownRecord",new XAttribute("GameID","new-id"))}){Reset(oldGame,newGame,reference);blocked=await service.PreviewAsync(settings,new[]{elf2});Check(blocked.Items.Single().Action=="NeedsReview","unknown field/attribute game references block removal");}
  var retainedReference=new XElement(oldGame);retainedReference.SetElementValue("RelatedGameID","new-id");Reset(retainedReference,newGame);blocked=await service.PreviewAsync(settings,new[]{elf2});Check(blocked.Items.Single().Action=="NeedsReview","unknown related-game references remain valid by blocking combination");
  var staleLegacy=new XElement(oldGame);staleLegacy.SetElementValue("ApplicationPath",Path.Combine("..","OldLocation","UserProfiles",legacy.Id+".xml"));Reset(staleLegacy,newGame);var repair=await service.PreviewAsync(settings,new[]{elf2});Check(repair.Items.Single().Action=="Combine","moved original profile still forms the exact loader pair");await service.ApplyAsync(repair);var legacyApp=XDocument.Load(platform).Root!.Elements("AdditionalApplication").Single(e=>(string?)e.Element("Version")==legacy.Id);Check(Path.GetFullPath(Path.Combine(lb,legacyApp.Element("ApplicationPath")!.Value))==legacy.UserProfilePath,"legacy launch option uses the current verified profile location");
  Reset(newGame,new XElement(newGame));blocked=await service.PreviewAsync(settings,new[]{elf2});Check(blocked.Items.Single().Action=="NeedsReview","two same-profile main games remain duplicate conflicts without mirror exceptions");
  var unknownExternal=Path.Combine(lb,"Data","CustomLinks.xml");Reset(oldGame,newGame);new XElement("LaunchBox",new XElement("UnknownLink","new-id")).Save(unknownExternal);blocked=await service.PreviewAsync(settings,new[]{elf2});Check(blocked.Items.Single().Action=="NeedsReview"&&!blocked.CanApply,"unsupported external references remain review blockers");File.Delete(unknownExternal);
  var usOld=Profile("VoyagerUs","Star Trek Voyager (USA)","Lindbergh");var usNew=Profile("VoyagerUsElf2","Star Trek Voyager (USA) (ElfLoader2)","ElfLdr2");var jpOld=Profile("VoyagerJapan","Star Trek Voyager (Japan)","Lindbergh");
  var usOldGame=Game("us-old-id",usOld,4);var usNewGame=Game("us-new-id",usNew,8);var jpGame=Game("jp-id",jpOld,2);var jpVersion=new XElement("AdditionalApplication",new XElement("Id","jp-version"),new XElement("GameID","jp-id"),new XElement("ApplicationPath",jpOld.UserProfilePath),new XElement("UseEmulator",true),new XElement("EmulatorId","emu"),new XElement("AutoRunBefore",false),new XElement("AutoRunAfter",false));var jpTool=new XElement("AdditionalApplication",new XElement("Id","jp-tool"),new XElement("GameID","jp-id"),new XElement("ApplicationPath","manual-tool.exe"),new XElement("AutoRunBefore",false),new XElement("AutoRunAfter",false));
  Reset(usOldGame,usNewGame,jpGame,jpVersion,jpTool);var mixedOriginal=File.ReadAllBytes(platform);var mixed=await service.PreviewAsync(settings,new[]{usOld,usNew,jpOld});Check(mixed.Items.Single(i=>i.ProfileId==usNew.Id).Action=="Consolidate"&&mixed.Items.Single(i=>i.ProfileId==usNew.Id).GameGuid=="us-new-id","mixed locales/loaders retain the preferred USA ELF2 game ID");await service.ApplyAsync(mixed);var mixedDoc=XDocument.Load(platform);var mixedGame=mixedDoc.Root!.Elements("Game").Single();Check((string?)mixedGame.Element("ID")=="us-new-id"&&(string?)mixedGame.Element("PlayCount")=="14","mixed family removes extra visible games and sums their history");var mixedApps=mixedDoc.Root.Elements("AdditionalApplication").ToList();Check(mixedApps.Count==3&&!mixedApps.Any(e=>(string?)e.Element("Id")=="jp-version")&&mixedApps.Single(e=>(string?)e.Element("Id")=="jp-tool").Element("GameID")!.Value=="us-new-id","nonpreferred regional AA removed while manual tool follows surviving parent");Check(mixedApps.Any(e=>(string?)e.Element("Version")==usOld.Id)&&mixedApps.Any(e=>(string?)e.Element("Version")==usNew.Id),"only the matching USA original loader remains as an alternate");Check(File.ReadAllBytes(mixed.BackupPath).SequenceEqual(mixedOriginal),"all removed regional/loader XML is backed up");Check(!(await service.PreviewAsync(settings,new[]{usOld,usNew,jpOld})).CanApply,"mixed consolidation is idempotent");
  Reset(usOldGame,usNewGame,jpGame,jpVersion,jpTool);new XElement("LaunchBox",new XElement("UnknownApplicationLink","jp-version")).Save(unknownExternal);blocked=await service.PreviewAsync(settings,new[]{usNew});Check(blocked.Items.Single().Action=="NeedsReview","unknown references to a removed regional application ID block cleanup");File.Delete(unknownExternal);
  var automaticRegional=new XElement(jpVersion);automaticRegional.SetElementValue("AutoRunBefore",true);Reset(usOldGame,usNewGame,jpGame,automaticRegional);blocked=await service.PreviewAsync(settings,new[]{usNew});Check(blocked.Items.Single().Action=="NeedsReview","automatic nonpreferred regional launch options remain review blockers");
  Reset(oldGame,newGame);var incompatible=Profile("StarTrekVoyagerJapan","Star Trek Voyager (Japan) (ElfLoader2)","ElfLdr2");Reset(oldGame,Game("japan-id",incompatible,1));blocked=await service.PreviewAsync(settings,new[]{incompatible});Check(blocked.Items.Single().Action=="SkippedVariant"&&!blocked.CanApply,"subset cannot replace a preferred ready loader with another locale");
 }
}

