<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net10.0-windows</TargetFramework><UseWindowsForms>true</UseWindowsForms><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode><AssemblyName>ArcadeLibraryManager</AssemblyName><ApplicationIcon>app.ico</ApplicationIcon><Version>0.2.20</Version></PropertyGroup><ItemGroup><EmbeddedResource Include="app.ico"/><ProjectReference Include="../ArcadeLibraryManager.Core/ArcadeLibraryManager.Core.csproj"/><Content Include="../../assets/**/*"><Link>assets/%(RecursiveDir)%(Filename)%(Extension)</Link><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory></Content></ItemGroup></Project>


